In [1]:
import pandas as pd

In [2]:
samples = [
    "cc4_1", "cc4_2", "cc4_3",
    "cd4_1", "cd4_2", "cd4_3",
    "mc4_1", "mc4_2", "mc4_3",
    "md4_1", "md4_2", "md4_3",
    "fc4_1", "fc4_2", "fc4_3",
    "fd4_1", "fd4_2", "fd4_3",
]

In [5]:
for s in samples:
    print(s)
    samplefile = f"../results_metaspades/{s}/amr_finderplus/log.out"
    df = pd.read_csv(samplefile, sep="\t")
    print(df.iloc[:, [1,2,3]])
    print("============")

cc4_1
                             Contig id  Start  Stop
0  NODE_61754_length_2049_cov_2.316430   1039  1455
1  NODE_61754_length_2049_cov_2.316430   1527  1874
2  NODE_61754_length_2049_cov_2.316430   1893  2048
============
cc4_2
                             Contig id  Start  Stop
0  NODE_14286_length_7676_cov_7.093433   7206  7676
1  NODE_29155_length_5001_cov_4.642973   4517  4999
2   NODE_9800_length_9602_cov_4.220892   5773  6132
3   NODE_9800_length_9602_cov_4.220892   7887  8129
4   NODE_9800_length_9602_cov_4.220892   8138  8407
5   NODE_9800_length_9602_cov_4.220892   8426  8773
6   NODE_9800_length_9602_cov_4.220892   8845  9261
============
cc4_3
                              Contig id  Start  Stop
0  NODE_112940_length_2377_cov_2.327826      1  1017
1  NODE_112940_length_2377_cov_2.327826   1324  1644
2  NODE_112940_length_2377_cov_2.327826   1644  1877
3   NODE_16236_length_8057_cov_7.137719   7542  8057
4   NODE_22665_length_6617_cov_3.840520   1787  2146
5   NODE_22665_length_6617_cov_3.840520   3810  4052
6   NODE_22665_length_6617_cov_3.840520   4061  4330
7   NODE_22665_length_6617_cov_3.840520   4349  4696
8   NODE_22665_length_6617_cov_3.840520   4768  5184
9   NODE_93789_length_2686_cov_5.027980    126   677
============
cd4_1
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
cd4_2
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
cd4_3
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
mc4_1
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
mc4_2
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
mc4_3
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
md4_1
                             Contig id  Start  Stop
0  NODE_34424_length_2696_cov_3.369225   1926  2696
============
md4_2
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
md4_3
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fc4_1
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fc4_2
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fc4_3
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fd4_1
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fd4_2
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============
fd4_3
Empty DataFrame
Columns: [Contig id, Start, Stop]
Index: []
============

In [71]:

samples_df = {}

all_gene_symbol = []

for s in samples:
#     print(s)
    samplefile = f"../results_metaspades/{s}/amr_finderplus/log.out"
    df = pd.read_csv(samplefile, sep="\t")
    df.rename(columns={"Gene symbol": "gene_symbol"}, inplace=True)
    
    all_gene_symbol += list(df.gene_symbol.unique())
    grp = df.groupby(by=["gene_symbol"]).count().reset_index().loc[:,["gene_symbol", "Contig id"]]
    
    samples_df[s] = grp
    

    
    
unique_gene_symbol = set(all_gene_symbol)

m = pd.DataFrame({"gene_symbol": list(unique_gene_symbol)})
m

for s, sdf in samples_df.items():
    sdf.rename(columns={"Contig id": s}, inplace=True)
    m = pd.merge(m, sdf, how="left", on="gene_symbol")

In [72]:
m

,gene_symbol,cc4_1,cc4_2,cc4_3,cd4_1,cd4_2,cd4_3,mc4_1,mc4_2,mc4_3,md4_1,md4_2,md4_3,fc4_1,fc4_2,fc4_3,fd4_1,fd4_2,fd4_3
0,merE,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,blaRATA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,merR,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,merD,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,merF,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,merT,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,merP,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,aacA32,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,merA,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
example = "../results_metaspades/cc4_1/amr_finderplus/log.out"Error(
   2427         f"Can only merge Series or DataFrame ob

In [30]:
df = pd.read_csv(example, sep="\t")Error(
   2427         f"Can only merge Series or DataFrame obError(
   2427         f"Can only merge Series or DataFrame ob
# df.head()

In [21]:
grp = df.groupby(by=["Contig id", "Gene symbol"]).count().reset_index()

grp.loc[:, ["Gene symbol", "Start"]]

  Gene symbol  Start
0        merP      1
1        merR      1
2        merT      1

In [29]:
m = pd.DataFrame({"Gene symbol": ["mrs"]})
mError(
   2427         f"Can only merge Series or DataFrame ob

  Gene symbol
0         mrs

In [26]:
m = pd.merge(m, grp, how="left")

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False